create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  preferred_style text,
  created_at timestamptz default now()
);
create table if not exists public.saved_looks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  occasion text not null,
  style text not null,
  season text,
  formality text,
  color text,
  score integer,
  title text,
  pieces jsonb,
  created_at timestamptz default now()
);
create table if not exists public.outfit_reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  image_path text,
  ai_score numeric,
  feedback jsonb,
  created_at timestamptz default now()
);
alter table public.profiles enable row level security;
alter table public.saved_looks enable row level security;
alter table public.outfit_reviews enable row level security;
create policy "profiles own row" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "saved looks own rows" on public.saved_looks for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "reviews own rows" on public.outfit_reviews for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,new.raw_user_meta_data->>'display_name') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
