"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import AuthNav from "../components/AuthNav";
import { useState } from "react";

const occasions=[['work','Work'],['party','Party'],['date','Date Night'],['travel','Travel'],['casual','Casual'],['evening','Evening']];
const styles=['Minimal','Classic','Street','Elegant','Trendy','Relaxed'];
const seasons=['Spring','Summer','Autumn','Winter'];
const formalities=['Relaxed','Smart Casual','Formal'];
const colors=['Neutrals','Earth Tones','Monochrome','Pastels','Bold Colors'];

export default function HomePage(){
 const router=useRouter(); const [occasion,setOccasion]=useState(''); const [style,setStyle]=useState(''); const [season,setSeason]=useState('Summer'); const [formality,setFormality]=useState('Smart Casual'); const [color,setColor]=useState('Neutrals'); const [error,setError]=useState('');
 function build(){if(!occasion||!style){setError('Choose an occasion and style first.');return;} const q=new URLSearchParams({occasion,style,season,formality,color});router.push(`/recommendations?${q}`)}
 return <main className="wearwise-page">
  <nav className="ww-nav"><Link href="/" className="ww-logo"><span className="ww-logo-mark">W</span>WEARWISE</Link><div className="ww-nav-links"><a href="#occasions">Occasions</a><a href="#finder">Style Finder</a><Link href="/upload">Rate My Outfit</Link></div><AuthNav/></nav>
  <section className="hero"><div className="hero-copy"><div className="eyebrow">✦ YOUR PERSONAL STYLE ASSISTANT</div><h1>Dress well.<br/><em>Everywhere.</em></h1><p>Discover outfits designed around your occasion, personal style, season and color preferences.</p><div className="hero-actions"><a href="#finder" className="primary-button">Find My Outfit ↗</a><Link href="/upload" className="secondary-button">Rate My Outfit</Link></div></div><div className="hero-visual"><div className="hero-card-back"/><div className="hero-fashion-card"><div className="fashion-card-top"><span>WEARWISE</span><span>STYLE / 01</span></div><div className="fashion-person"><div className="person-head"/><div className="person-body"><div className="shirt"/><div className="pants"/></div></div><div className="fashion-card-bottom"><div><small>TODAY'S DIRECTION</small><strong>Smart & effortless</strong></div><div className="style-score">8.8</div></div></div></div></section>
  <section className="quick-strip"><div><strong>01</strong><span>Choose your moment</span></div><div><strong>02</strong><span>Define your style</span></div><div><strong>03</strong><span>Build your look</span></div><div><strong>04</strong><span>Make it yours</span></div></section>
  <section className="discovery-section" id="occasions"><div className="section-heading"><div><span className="section-label">STYLE DISCOVERY</span><h2>Dress for<br/>the moment.</h2></div><p>Choose an occasion and WearWise will build a coordinated direction for it.</p></div><div className="occasion-grid">{occasions.map(([id,title],i)=><button key={id} className={`occasion-card occasion-${id}`} onClick={()=>{setOccasion(id);document.getElementById('finder')?.scrollIntoView({behavior:'smooth'})}}><div className="occasion-number">0{i+1}</div><div className="occasion-symbol">{['▣','✦','♡','↗','○','☾'][i]}</div><div className="occasion-content"><span>STYLE FOR THE MOMENT</span><h3>{title}</h3></div><div className="occasion-arrow">↗</div></button>)}</div></section>
  <section className="finder-section" id="finder"><div className="finder-panel"><div className="finder-intro"><span className="section-label">WEARWISE ENGINE</span><h2>Build your<br/><em>perfect look.</em></h2><p>Tell us what you are dressing for and WearWise will return a complete outfit with actual clothing visuals.</p><div className="engine-status"><span/>Recommendation engine ready</div></div><div className="finder-controls">{[['OCCASION',occasions.map(x=>x)],['YOUR STYLE',styles],['SEASON',seasons],['FORMALITY',formalities],['COLOR DIRECTION',colors]].map(([label,items],group)=><div className="finder-group" key={label}><span className="finder-label">0{group+1} — {label}</span><div className="finder-options">{items.map(item=>{const value=Array.isArray(item)?item[0]:item;const text=Array.isArray(item)?item[1]:item;const selected=[occasion,style,season,formality,color][group]===value;return <button type="button" key={value} className={selected?'finder-option active':'finder-option'} onClick={()=>[setOccasion,setStyle,setSeason,setFormality,setColor][group](value)}>{text}</button>})}</div></div>)}{error&&<div className="finder-error">{error}</div>}<button className="finder-submit" onClick={build}>Generate My Outfit ↗</button><p className="finder-note">No account required to generate a look.</p></div></div></section>
  <section className="upload-section"><div className="upload-card"><div className="upload-copy"><span className="section-label">OUTFIT OF THE DAY</span><h2>How did you<br/><em>dress today?</em></h2><p>Upload an outfit for a free WearWise demo review. Real vision AI can be connected later.</p><Link href="/upload" className="upload-button">Upload My Outfit ↗</Link></div><div className="upload-preview"><div className="upload-frame"><div className="upload-plus">+</div><strong>Your next look</strong><span>Upload a photo to begin</span></div></div></div></section>
  <footer className="ww-footer"><Link href="/" className="ww-logo"><span className="ww-logo-mark">W</span>WEARWISE</Link><span>Your style. Your rules.</span><span>© 2026 WearWise</span></footer>
 </main>
}
